
./scripts/build_pkg-config.sh
./scripts/build_aom.sh
./scripts/build_fontconfig.sh
./scripts/build_freetype.sh
./scripts/build_harfbuzz.sh
./scripts/build_kvazaar.sh
./scripts/build_lame.sh
./scripts/build_libass.sh
./scripts/build_libbluray.sh
./scripts/build_libopus.sh
./scripts/build_libtheora.sh
./scripts/build_libvorbis.sh
./scripts/build_libwebp.sh
./scripts/build_libzimg.sh
./scripts/build_openjpeg.sh
./scripts/build_snappy.sh
./scripts/build_svtav1.sh
./scripts/build_vidstab.sh
./scripts/build_vpx.sh
./scripts/build_x264.sh
./scripts/build_x265.sh
./scripts/build_ffmpeg.sh
